name: 'Create Sops Secret'
description: 'Create and Encrypt sops secrets for isindir/sops-secrets-operator'
inputs:
  prefix:
    description: the prefix of the repository github secrets to include
    required: true
  file_path:
    description: the path to write the file, the name of the secret is derived as basename
    required: true
  json_secrets_str:
    description: >
      json encoded list of secrets.
    required: true
runs:
  using: composite
  steps:
  - shell: bash
    env:
      PREFIX: ${{ inputs.prefix }}
      FILE_PATH: ${{ inputs.file_path }}
      JSON_SECRETS_STR: ${{ inputs.json_secrets_str }}
    run: |
      mkdir -p `dirname ${FILE_PATH}`
      FILE_NAME=${FILE_PATH##*/}
      SECRET_NAME=${FILE_NAME%.*}
      cat <<'EOF' > filter.jq
      with_entries( select(.key | startswith($prefix)) | .key = (.key | sub($prefix; "")) ) | {
        "apiVersion": "isindir.github.com/v1alpha2",
        "kind": "SopsSecret",
        "metadata":{
          "name": $name,
          "annotations": {
            "secret-names.cag.codes": $name
          }
        },
        "spec":{
          "secretTemplates": [
            {
              "name": $name,
              "data": .
            }
          ]
        }
      }
      EOF

      jq -f filter.jq --arg name "${SECRET_NAME}" --arg prefix "${PREFIX}" <<< ${JSON_SECRETS_STR} \
        | sops -e --input-type="json" --output-type="yaml" /dev/stdin > ${FILE_PATH}
      rm filter.jq
