name: "Functional Tests"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  functional-tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
        # using https://github.com/mozilla/sops/blob/v3.7.1/pgp/sops_functional_tests_key.asc
      - run: gpg --import pgp/sops_functional_tests_key.asc
      - uses: mdgreenwald/mozilla-sops-action@v1.1.0
        with:
          version: v3.7.1
      - uses: ./
        with:
          json_secrets_str: ${{ toJSON(secrets) }}
          prefix: STAGING_ENV_
          file_path: tests/env-secrets.yaml
      - uses: ./
        with:
          json_secrets_str: ${{ toJSON(secrets) }}
          prefix: STAGING_CERT_
          file_path: tests/certs.yaml
      - run: |
          sops -d tests/env-secrets.yaml
          sops -d tests/certs.yaml
